### ISSUE TITLE
Analytics: todo

### ISSUE THREAD

**Issue by WouterSioen** [forkcms/forkcms#1200]
Some functionality could be useful to add in the new version of the analytics module.

- [x] Add a reset functionality
- [ ] Possibly add the "google_adwords" option again (classic analytics will be deprecated, so I won't add this again)
- [x] Dashboard widget(s)
- [x] Most visited pages
- [ ] ...
