### ISSUE TITLE
Symfony integration

### ISSUE THREAD

**Issue by WouterSioen** [forkcms/forkcms#1714]
- [x] Replace SpoonCookie/SpoonSession with Request/Response object #399
- [x] Refactor Fork hooks using EventDispatcher #405
- [ ] Refactor locale module using Translation #408
- [ ] Refactor Fork and Pages with Routing component #409
- [ ] Replace SpoonThumbnail/SpoonFile #708
- [x] Refactor out all exit statements #1105
- [ ] Refactor out constants #1106
- [x] Refactor API #1142
- [x] Refactor out SpoonFilter::getGetValue and SpoonFilter::getPostValue #1347
## Replace SpoonCookie/SpoonSession with Request/Response object #399

We need to pass a response object to every action/widget/... that can manipulate the sessions and cookies.
## Refactor Fork hooks using EventDispatcher #405

step 1: delete all triggerEvents + deprecate the triggerEvent method
step 2: add events for everything
## Refactor Fork and Pages with Routing component #409

We already use the router for our applications. We can probably use the ChainedRouter to do the further routing in the frontend based on our Pages module.
## Replace SpoonThumbnail/SpoonFile #708

There's probably a package for this.
## Refactor out all exit statements #1105

Replace them with good clear exceptions. This will also help us test more stuff.

Done in #1797
## Refactor out constants #1106

Container parameters are the way to go
## Remove API #1142

The API needs to be deprecated and altered by an easy way to add new API endpoints. This will also fix the usage of SpoonTemplate. 

We can use a combination of bundles to achieve these results (https://github.com/nelmio/NelmioApiDocBundle, https://github.com/FriendsOfSymfony/FOSRestBundle, ...)
## Refactor out SpoonFilter::getGetValue and SpoonFilter::getPostValue #1347

We should use the request object for this.

**Comment by myspulin** [comment]
Hi, I do some development on the last version API and I wonder why is class BaseApi deprecated. In the comments there was mentioned bundle NelmioApiDocBundle or FOSRestBundle is it already decided which one will be used? Is there any estimation when will be implemented? Thanks for info.

**Comment by myspulin** [comment]
@jessedobbelaere, thanks for update, it make sense to remove legacy code first I cant wait for new version. Regarding FOSRestbundle I will try the Slack and ask the others. Thank you!

**Comment by carakas** [comment]
@myspulin you can find a demo implementation of the FOSRestBundle here https://github.com/forkcms/forkcms/compare/master...justcarakas:rest-api-challange

**Comment by jeroendesloovere** [comment]
Interesting article about using "keys" for "translations".
http://obtao.com/blog/2013/06/how-to-organize-your-translations-in-symfony/

**Comment by carakas** [comment]
No longer needed to keep a separate issue for this as we do it when and where we can
