### ISSUE TITLE
CLI developer tools

### ISSUE THREAD

**Issue by WouterSioen** [forkcms/forkcms#1715]
## Type
- Enhancement
## Problem description

Developer tools should be moved to the CLI
- [ ] Module generator (in progress)
- [ ] Module uninstaller #872
- [ ] Modules extras viewer/editor #874
- [ ] Edit and check modules extra in the backend #959
- [ ] Add a "delete theme" action #1484
- [x] Replace all cronjobs with cli commands. #1631
- [x] Command to enable a language #1689 (in progress)

**Comment by carakas** [comment]
closing for now, nobody implemented these anymore, if someone still wants one of these they can but I see no need to keep this issue open. Also uninstalling a module isn't as simple because there can be a lot of side effects in the installer
