### ISSUE TITLE
WIP: Entities

### ISSUE THREAD

**Issue by tijsverkoyen** [forkcms/forkcms#2369]
## Type

- Enhancement

## Problem description

Just an issue to track some todo's for when we have finished converting the modules to use entities

## Todo's

* [ ] Check if all fixtures use entities where possible
* [ ] `Meta` entity should be stored in table `Meta` instead of `meta`
* [ ] Once there is a `User` entity, all relevant modules should be updated to use this instead of a integer reference
* [ ] Tests should contain more consistent data
* [ ] Check if all correct methods are implemented in the repositories
* [ ] Check if all methods that appear in repositories have consistent signatures
* [ ] Check if we can remove SpoonDatabase (in tests)

**Comment by jeroendesloovere** [comment]
@tijsverkoyen, we should also create a `ModuleExtra` entity.

**Comment by carakas** [comment]
this is included in rewriting the modules so it doesn't need to be a separate issue
