### ISSUE TITLE
Refactoring towards folder structure of Symfony 4.*

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2399]
# Type

- Enhancement

## Problem description

Refactor to support Symfony 4.*. Currently we are using Symfony 3.3.*. (edited)

## Steps to reproduce

Follow the [symfony 4.0 upgrade guide](https://github.com/symfony/symfony/blob/master/UPGRADE-4.0.md).

## Soft Namespace changes (file movements, namespace changes, class name changes):

= Trying to use `"App\\": "src",` and get rid of:
```
"Frontend\\": "src/Frontend",
"Backend\\": "src/Backend",
"Common\\": "src/Common",
"Console\\": "src/Console",
"ForkCMS\\": "src/ForkCMS",
"ForkCMS\\App\\": "app",
```
And refactoring to [this folder structure](https://gist.github.com/jeroendesloovere/87295062f4281d79cdc90fd882582a71)
- [x] Create `App\Component` (containing `Asset`, `Header`, `Priority`, `Uri`), #2435 
- [x] Create `App\Domain\Meta`, #2433  
- [x] Create `App\Domain\ModuleExtra`, #2434 
- [x] Create `App\Service\Doctrine\EntitySchema`, #2432
- [x] Create `App\Service\Mailer` and `App\Tests\Service\Mailer` namespaces, #2436 
- [x] Create `App\Twig` (renaming `Common\Core\Twig`), #2437
- [x] Create `App\EventListener` (renaming `Common\EventListener`), #2439
- [x] Create `App\Exception` (renaming `Common\Exception`), #2440
- [x] Create `App\Form` (renaming `Common\Form`) and move the remaining `Common\Doctrine` files to this folder.
- [x] Where should we place `Common\DataCollector\DatabaseDataCollector.php`?
- [x] Remove unused imports
- [x] Move Backend/Cache (#cd408aa) and Frontend/Cache (#a1c336b)
- [x] Refactor ForkCMS\Bundle\CoreBundle, #5a12bec
- [x] Refactor ForkCMS\Bundle\InstallerBundle
- [x] Rework `ModuleSettings` (and its test) to `App\Domain\ModuleSetting` and a `App\Service\Module\ModuleSettings.php`
- [x] Move `src/Console/Core/CacheClearCommand.php` to `src/Console/Cache/CacheClearCommand.php` which makes more sense (since everything is already core, that is a bad name).
- [x] Uniform `forkcms` service declaration, use `forkcms.` instead of `fork.` (#c920a4c)
- [x] Move `Frontend/Files` to `public`
- [ ] DependencyInjection: container services are now private by default. If you want them public, you must explicitly define it.
- [ ] Create `App\Domain\ModuleSetting` Entity/Repository + refactor SpoonDatabase out in `App\Service\Module\ModuleSettings`.
- [ ] All bin vendors should be in the default `vendor/bin`

## Hard breaking changes:
- [ ] Move Frontend/Backend/Core css/fonts/images to `assets` or `public` like `symfony-4` requires. (Probably also using Webpack Encore would be a good idea) + We need to get rid of `/var/backend/MinifiedCss`, `/var/backend/MinifiedJs `, /var/frontend/MinifiedCss`, `/var/backend/MinifiedJs`, because these should be in `public/build`.
- [ ] `app/Kernel.php` (and all similar files) should be replaced by `src/Kernel.php` and symfony 4.
- [ ] Refactor `Backend\Core\Ajax\` `GenerateUrl`, `Templates` and `UpdateSequence` to `src/Controller/BackendAjaxController.php` methods.
- [ ] Load in latest symfony

... see the symfony 4.0 upgrade guide...

**Comment by carakas** [comment]
We are currently using symfony 3.3 not 3.2
And fork 5.1 will be symfony 3.4 and if you don't have any deprecation warnings there we kan flip the switch, most deprecation warnings will be fixed in 5.1 already

**Comment by jeroendesloovere** [comment]
Closing this one, because this PR goes to far to merge properly
