### ISSUE TITLE
Ckeditor 'add link' functionality is too minimalistic  

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2524]
## Type

- Enhancement

## Problem description
The functionalities to easy add a mailto link or open a link in a new tab are all gone, why?

now
![image](https://user-images.githubusercontent.com/12270833/38307547-55eeb822-3814-11e8-92a9-3cc9809d434f.png)

before
![image](https://user-images.githubusercontent.com/12270833/38307600-74544200-3814-11e8-96fa-7cbfd4c83897.png)

## TO-DO

- [x] Internal pages [#2499](https://github.com/forkcms/forkcms/pull/2499)
- [x] URL (with protocol selector)
- [x] E-mail (with stuff like recipient, subject, ...)
- [x] anchor

**Comment by StijnVrolijk** [comment]
They're gone because we had to write a new plugin from scratch to hook in to the Media Library.
We are aware of the missing features and some improvements have been made already.

- Internal pages [#2499](https://github.com/forkcms/forkcms/pull/2499)

I'll add a to-do list to your post.

**Comment by ohvitorino** [comment]
In my opinion the protocol dropdown has no added value. I think most users will already have an url with a protocol. It feels silly to me to than have to paste the url, remove the protocol from the pasted text and select the correct one in the protocol dropdown.
I think the dropdown could have two values: Hyperlink and Email. If the user selects hyperlink than he can paste his url in the text field with protocol, on the other hand if he selects Email, than he could be presented with extra text fields for recipient, subject, etc.

**Comment by StijnVrolijk** [comment]
We could also add some JS that triggers whenever someone pastes something. We could then extract the protocol if available and select the correct protocol in the dropdown. This ensures we always have a protocol without having to annoy non-tech-savvy users with 'This is not a valid URL'.
